FROM ruby:2.3.3
MAINTAINER David Inga <david.inga@vizzuality.com>

ENV RAILS_ENV development
ENV RACK_ENV development

# Install dependencies
RUN apt-get update && apt-get install -y \
      build-essential \
      imagemagick \
      bash \
      git \
      nodejs \
      tzdata \
      libxml2-dev \
      libxslt-dev \
      postgresql postgresql-contrib \
      --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && bundle config build.nokogiri --use-system-libraries \
    && gem install bundler --no-ri --no-rdoc \
    && mkdir -p /usr/src/i2i

WORKDIR /usr/src/i2i
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN bundle install --jobs 20 --retry 5
ADD . /usr/src/i2i
