version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./.data:/var/lib/postgresql/data
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bundle exec rails server -b 0.0.0.0
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - PORT=3000
      - RAILS_ENV=development
      - RACK_ENV=development
      - REDIS_HOST=redis
    volumes:
      - "./:/usr/src/i2i"
      - "./public/uploads:/usr/src/i2i/public/uploads"
      - "./public/system:/usr/src/i2i/public/system"
      - "./db/data:/usr/src/i2i/db/data"
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    container_name: i2i_redis
    ports:
      - 6789:6789
    volumes:
      - redis:/data
volumes:
  redis: {}
