FROM ruby:2.5.3-alpine

RUN apk update && apk add --no-cache \
  build-base bash git nodejs yarn postgresql-dev imagemagick tzdata

WORKDIR /usr/src/i2i
COPY Gemfile Gemfile.lock package.json yarn.lock ./
RUN bundle install --jobs `expr $(cat /proc/cpuinfo | grep -c "cpu cores") - 1` --retry 3
RUN yarn install && yarn cache clean
ADD . ./
