version: '3'
services:
  web:
    container_name: i2i_app_dev
    build:
      context: .
      args:
        - env=development
    command: bin/rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    volumes:
      - "./app:/usr/src/i2i/app"
